spring:
  datasource:
    url: jdbc:postgresql://10.140.0.3:5432/postgresql
    username: postgresql
    password: postgrespassword
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  rabbitmq:
    host: 10.174.0.12
    username: guest
    password: guest
    port: 5672
  data:
    elasticsearch:
      hosts: 10.174.0.13,10.174.0.14,10.174.0.15,10.146.0.3
      port: 9200